// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juibsxmelzhtfveclhcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1aWJzeG1lbHpodGZ2ZWNsaGNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjE4NzcsImV4cCI6MjA1NjkzNzg3N30.wcVhZ7hrQzjiQCShF_KamKV_EinTxceIyNheMr19kgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);